version: '3.8'

services:
  db:
    image: postgres:16
    container_name: movie_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${SPRING_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_travelAiNetwork

  redis:
    image: redis:8.0.6-alpine3.21
    container_name: project_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - my_travelAiNetwork

networks:
  my_travelAiNetwork:
    driver: bridge

volumes:
  db_data:
  redis_data: