spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${SPRING_DATABASE_USERNAME}
spring.datasource.password=${SPRING_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
security.jwt.expirationTime=1800000
security.jwt.refreshExpirationTime=${EXPIRATION_TIME_FOR_REFRESH_TOKEN}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST}
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.security=DEBUG
#okta.oauth2.issuer=https://<your-auth0-domain>/
#okta.oauth2.audience=${okta.oauth2.issuer}api/v2/
#okta.oauth2.client-id=${CLIENT_ID}
#okta.oauth2.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=redis
tmdb.api.base-url=https://api.themoviedb.org/3/
tmdb.api.token=${TMDB_API_TOKEN}
spring.config.import=optional:file:.env[.properties]